exclude: [Gemfile, Gemfile.lock, Procfile, config.rb, sass]
safe: true
lsi: false
pygments: true

permalink: /:categories/:title

markdown: redcarpet

redcarpet:
  extensions: ["hard_wrap", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]
