exclude: [Gemfile, Gemfile.lock, Procfile, config.rb, sass]
safe: false
lsi: false
highlighter: pygments

permalink: /:categories/:title

markdown: redcarpet

redcarpet:
  extensions: ["hard_wrap", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]

gems:
  - jekyll-sitemap

url: http://billt.me
name: BillT.me
author:
  name: Bill Thornton
  email: bill@billt.me
description: BillT.me is a blog about web development and related technologies that I find interesting.
